# @package dataset
name: Mini-Imagenet
root: ${hydra:runtime.cwd}/datasets/Mini-Imagenet/
batch_size: 128
test_batch_size: ${dataset.batch_size}
max_threads: 12
validation_split: 0.1
fixed_shuffle: true